name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - run: kotlin pack.main.kts
      - uses: softprops/action-gh-release@v1
        with:
          files: empty_exception_messages.zip
